### ISSUE TITLE
Which Linter?

### ISSUE THREAD

**Issue by hobeygo** [alexbarten/devguides#1]
Hi Alex,

Would you consider covering linters in python/vscode in your next iteration?

Regards,
Onur

**Comment by alexbarten** [comment]
Hi Onur,

I will. Thanks for your suggestion.
--
Kind regards,

Alex

**Comment by alexbarten** [comment]
Hi Onur, 

The latest commit, which I just pushed, adds a section on linters. I hope you like it.

Kind regards,

Alex
