### ISSUE TITLE
Adding pytest in Visual Studio Code 

### ISSUE THREAD

**Issue by highsmallxu** [alexbarten/devguides#3]
**How to add pytest in Visual Studio Code**

1. [Enable a test framework](https://code.visualstudio.com/docs/python/unit-testing#_enable-a-test-framework)
add the following configuration in _settings.json_ 
It's important to enable one test framework at one time. 
```
"python.unitTest.unittestEnabled": false,
"python.unitTest.pyTestEnabled": true,
"python.unitTest.nosetestsEnabled": false,
```

2. [Run tests](https://code.visualstudio.com/docs/python/unit-testing#_run-tests)
Just right click the test_xx.py file and choose `Run all Unit Tests`

3. If you click 18Run Test(Multiple), you can also select individual test that you want to run
    <img width="236" alt="Capture" src="https://user-images.githubusercontent.com/10590557/55469942-e4354680-5606-11e9-82df-5a6dccaa3097.PNG">

Pytest-BDD is currently not supported in Visual Studio Code. 

More information is on [this page](https://code.visualstudio.com/docs/python/unit-testing)

**Comment by alexbarten** [comment]
Hi Xiaoxu,  

Thanks. I will add a section on test runners in general and pytest in particular as soon as I have time to do so. I will also refer to the online documentation, as this information is partly described there. The goal of my document is to enable navigation through these sections, and to describe what has not been mentioned in the manuals.  

Later on, I will add info about BDD. The beauty of BDD is that you do not really need support of an editor - it does not add much. Test runner support and BDD syntax highlighting support is sufficient (and VSCode does that). Until then you can use the pytest-bdd command from the command line within VSCode. I will add that.   

Expect an update to this issue.  

Kind regards,  
Alex

**Comment by alexbarten** [comment]
I have added a section on Unit Testing. Mostly to have a landing section to refer to the excellent Python Unit Test chapter in the VSCode docs.

**Comment by alexbarten** [comment]
Just added: a new section on pytest-bdd. Issue closed.
